export enum TaskType {
  LAUNCH_BROWSER = "LAUNCH_BROWSER",
  // NAVIGATE_TO_URL = "NAVIGATE_TO_URL",
  // CLICK_ELEMENT = "CLICK_ELEMENT",
  // INPUT_TEXT = "INPUT_TEXT",
  // CHECK_ELEMENT_VISIBLE = "CHECK_ELEMENT_VISIBLE",
  // CHECK_ELEMENT_NOT_VISIBLE = "CHECK_ELEMENT_NOT_VISIBLE",
}
